# Generated by Django 5.1.1 on 2024-09-23 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Waiting Apruval', 'Waiting Apruval'), ('active', 'active'), ('delete', 'delete')], default='active', max_length=255),
        ),
    ]
